// -*- C++ -*-
// AID-GENERATED
// =========================================================================
// This class was generated by AID - Abstract Interface Definition          
// DO NOT MODIFY, but use the org.freehep.aid.Aid utility to regenerate it. 
// =========================================================================
#ifndef GEAR_TELPLANESPARAMETERS_H
#define GEAR_TELPLANESPARAMETERS_H 1

#include "gear/GearParameters.h"

namespace gear {

class TelPlanesLayerLayout;

/**Geometry properties of a pixel beam telescope needed for reconstruction code.
   *  @author I. Rubinskiy, DESY
   *  @version $Id: 
   */
	
class TelPlanesParameters : virtual public GearParameters {

public: 
    /// Destructor.
    virtual ~TelPlanesParameters() { /* nop */; }


    /** ID of telescope setup.
     */

    virtual int getTelPlanesID() const = 0;

    /** The type of TelPlanes detector: 
     */

    virtual int getTelPlanesType() const = 0;

    /** Number of telescope planes of TelPlanes detector.
     */

    virtual int getTelPlanesNumber() const = 0;

    /** The layer layout of pixel beam telescope. */
    virtual const TelPlanesLayerLayout & getTelPlanesLayerLayout() const = 0;

}; // class
} // namespace gear
#endif /* ifndef GEAR_TELPLANESPARAMETERS_H */
