// -*- C++ -*-
// AID-GENERATED
// =========================================================================
// This class was generated by AID - Abstract Interface Definition          
// DO NOT MODIFY, but use the org.freehep.aid.Aid utility to regenerate it. 
// =========================================================================
#ifndef GEAR_TRACKERPLANESPARAMETERS_H
#define GEAR_TRACKERPLANESPARAMETERS_H 1

#include "gear/GearParameters.h"

namespace gear {

class TrackerPlanesLayerLayout;

/**Geometry properties of a pixel beam telescope needed for reconstruction code.
   *  @author I. Rubinskiy, DESY
   *  @version $Id: 
   */
	
class TrackerPlanesParameters : virtual public GearParameters {

public: 
    /// Destructor.
    virtual ~TrackerPlanesParameters() { /* nop */; }


    /** ID of telescope setup.
     */

    virtual int getTrackerPlanesID() const = 0;

    /** The type of TrackerPlanes detector: 
     */

    virtual int getTrackerPlanesType() const = 0;

    /** Number of telescope planes of TrackerPlanes detector.
     */

    virtual int getTrackerPlanesNumber() const = 0;

    /** The layer layout of pixel beam telescope. */
    virtual const TrackerPlanesLayerLayout & getTrackerPlanesLayerLayout() const = 0;

}; // class
} // namespace gear
#endif /* ifndef GEAR_TRACKERPLANESPARAMETERS_H */
